title: "Thymeleaf Layout Dialect"
description: "A dialect for Thymeleaf that lets you build layouts and reusable templates in order to improve code reuse"
baseurl: "/thymeleaf-layout-dialect"
theme: "just-the-docs"
